name: 'Java Setup Action'
description: 'Sets up Java environment'

inputs:
  java-version:
    description: 'Java version'
    required: true
    default: '17'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ inputs.gradle-version }}